version: '3'
services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./DB/data:/var/lib/mysql
      - ./DB/init:/docker-entrypoint-initdb.d
      - ./DB/config:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - TZ=Asia/Tokyo
    tty: true

  backend:
    build: ./
    container_name: go-api
    ports:
      - 8080:8080
    volumes:
      - ./:/go/src
    links:
      - db

