version: '3'
services:
  rdb:
    image: mysql:latest
    container_name: rdb
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./DB/data:/var/lib/mysql
      - ./DB/init:/docker-entrypoint-initdb.d
      - ./DB/config:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=${RDB_ROOT_PASSWORD}
      - MYSQL_USER=${RDB_USER}
      - MYSQL_PASSWORD=${RDB_USER_PASSWORD}
      - MYSQL_DATABASE=${RDB_NAME}
      - TZ=Asia/Tokyo
    tty: true

  redis:
    image: redis:latest
    container_name: redis

  backend:
    build: ./
    container_name: go-api
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/go/src
    links:
      - rdb
      - redis
